In [1]:
import numpy as np

# [ Array Generation Function ]

### `zeros()` : allocate an array of zeros 

In [2]:
np.zeros(4)

array([0., 0., 0., 0.])

In [3]:
np.zeros((4,))

array([0., 0., 0., 0.])

In [4]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

##### [NOTE] Distinguishing `4`, `(4)`, and `(4,)`
A tuple can be constructed by adding a `()` to a comma-separated sequence of objects.

For example, `(3,'star',5.5)` is a tuple with 3 elements.

When one wants to construct a tuple with 1 element, say a number `4`, it may be tempting to do so like `(4)`. However, it would be interpreted as just a scalar number `4` since a pair of `()` _without_ commas is reserved not for tuple but for other purpose such as directing an evaluation order.

Thus, when one wants to construct a tuple with one element, one should do so by appending a comma at the end of the first object, like `(4,)`

##### [NOTE] When specifying a shape, use tuple, rather than a scalar number.
A number and a tuple with one element should be distinguished. (e.g. `4` and `(4,)`)

When generating 1-D array using a function like `zeros()`, it is recommended to use tuple rather than just scalar number for enhanced consistency with the case of higher dimension array, although both are acceptable.

### `ones()` : allocate an array of ones

In [5]:
np.ones((6,))

array([1., 1., 1., 1., 1., 1.])

In [6]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### `linspace()` : allocate an array of equally (linearly) spaced numbers between fixed minimum and maximum

In [7]:
# I want to generate an array 
# with linearly spaced 11 numbers between 0 and 1
start, end, number = 0, 1, 11

In [8]:
a = np.linspace(start, end, number)

In [9]:
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [10]:
## interval
(end - start) / (number - 1)

0.1

In [11]:
## interval, assuming equidistance of a
a[1] - a[0]

0.1

### `eye()` allocate an identity matrix

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# [ Math functions ]

### Generate an test array

In [13]:
x = np.linspace(-1, 1, 20)

In [14]:
x

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

### `exp()`

In [15]:
np.exp(x)

array([0.36787944, 0.40871514, 0.45408372, 0.50448835, 0.56048804,
       0.62270386, 0.69182583, 0.76862053, 0.85393967, 0.94872948,
       1.05404124, 1.17104292, 1.30103213, 1.44545052, 1.60589978,
       1.78415938, 1.98220632, 2.20223705, 2.44669184, 2.71828183])

In [16]:
np.exp(1j * x)  # it also works for complex number

array([0.54030231-0.84147098j, 0.62572411-0.78004444j,
       0.70421909-0.70998273j, 0.77491828-0.63206143j,
       0.83703905-0.54714315j, 0.88989371-0.45616793j,
       0.93289715-0.36014289j, 0.96557333-0.26013102j,
       0.9875605 -0.15723948j, 0.99861528-0.05260728j,
       0.99861528+0.05260728j, 0.9875605 +0.15723948j,
       0.96557333+0.26013102j, 0.93289715+0.36014289j,
       0.88989371+0.45616793j, 0.83703905+0.54714315j,
       0.77491828+0.63206143j, 0.70421909+0.70998273j,
       0.62572411+0.78004444j, 0.54030231+0.84147098j])

### `sin()`, `cos()`, `tan()`

In [17]:
np.sin(x)

array([-0.84147098, -0.78004444, -0.70998273, -0.63206143, -0.54714315,
       -0.45616793, -0.36014289, -0.26013102, -0.15723948, -0.05260728,
        0.05260728,  0.15723948,  0.26013102,  0.36014289,  0.45616793,
        0.54714315,  0.63206143,  0.70998273,  0.78004444,  0.84147098])

In [18]:
np.cos(x)

array([0.54030231, 0.62572411, 0.70421909, 0.77491828, 0.83703905,
       0.88989371, 0.93289715, 0.96557333, 0.9875605 , 0.99861528,
       0.99861528, 0.9875605 , 0.96557333, 0.93289715, 0.88989371,
       0.83703905, 0.77491828, 0.70421909, 0.62572411, 0.54030231])

In [19]:
np.tan(x)

array([-1.55740772, -1.24662679, -1.00818444, -0.81564914, -0.65366502,
       -0.51260945, -0.38604779, -0.26940577, -0.1592201 , -0.05268023,
        0.05268023,  0.1592201 ,  0.26940577,  0.38604779,  0.51260945,
        0.65366502,  0.81564914,  1.00818444,  1.24662679,  1.55740772])

# [ Handling Complex-valued array ]

### Generate an test array

In [20]:
c1 = np.exp(1j * x)

### Accessing real part & imaginary part

In [21]:
c1.real

array([0.54030231, 0.62572411, 0.70421909, 0.77491828, 0.83703905,
       0.88989371, 0.93289715, 0.96557333, 0.9875605 , 0.99861528,
       0.99861528, 0.9875605 , 0.96557333, 0.93289715, 0.88989371,
       0.83703905, 0.77491828, 0.70421909, 0.62572411, 0.54030231])

In [22]:
c1.imag

array([-0.84147098, -0.78004444, -0.70998273, -0.63206143, -0.54714315,
       -0.45616793, -0.36014289, -0.26013102, -0.15723948, -0.05260728,
        0.05260728,  0.15723948,  0.26013102,  0.36014289,  0.45616793,
        0.54714315,  0.63206143,  0.70998273,  0.78004444,  0.84147098])

### Conjugation : $z^{*}=Re[z]+i{Im}[z]$

##### Using module function

In [23]:
np.conjugate(c1)

array([0.54030231+0.84147098j, 0.62572411+0.78004444j,
       0.70421909+0.70998273j, 0.77491828+0.63206143j,
       0.83703905+0.54714315j, 0.88989371+0.45616793j,
       0.93289715+0.36014289j, 0.96557333+0.26013102j,
       0.9875605 +0.15723948j, 0.99861528+0.05260728j,
       0.99861528-0.05260728j, 0.9875605 -0.15723948j,
       0.96557333-0.26013102j, 0.93289715-0.36014289j,
       0.88989371-0.45616793j, 0.83703905-0.54714315j,
       0.77491828-0.63206143j, 0.70421909-0.70998273j,
       0.62572411-0.78004444j, 0.54030231-0.84147098j])

##### Using array's own function (it is called 'method' of the array)

In [24]:
c1.conjugate()

array([0.54030231+0.84147098j, 0.62572411+0.78004444j,
       0.70421909+0.70998273j, 0.77491828+0.63206143j,
       0.83703905+0.54714315j, 0.88989371+0.45616793j,
       0.93289715+0.36014289j, 0.96557333+0.26013102j,
       0.9875605 +0.15723948j, 0.99861528+0.05260728j,
       0.99861528-0.05260728j, 0.9875605 -0.15723948j,
       0.96557333-0.26013102j, 0.93289715-0.36014289j,
       0.88989371-0.45616793j, 0.83703905-0.54714315j,
       0.77491828-0.63206143j, 0.70421909-0.70998273j,
       0.62572411-0.78004444j, 0.54030231-0.84147098j])

### Example : checking $e^{ix}=\cos(x)+i\sin(x)$

##### one-line version

In [25]:
np.exp(1j*x) == np.cos(x) + 1j * np.sin(x)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

##### Checking by part : real & imaginary

In [26]:
c1 = np.exp(1j * x)

In [27]:
c1.real == np.cos(x)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [28]:
c1.imag == np.sin(x)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

# [TIP] Using `Shift-Tab` to get a function's description
- Move cursor to the object that you want to see the description and press `Shift-Tab`
- Try and compare: `Shift-Tab`, `Shift-Tab-Tab`, ..., `Shift-Tab-Tab-Tab`