# [ Why NumPy? ]

**NumPy** is a package of tools for manipulating array of same-type objects.

Although the NumPy is useful, we can do what we want without this.

Then, why one should use NumPy?

Following sections demonstrates some advantages to use NumPy

In [1]:
import numpy as np

## Example: Calculating $x^3$ of several $x \in \{0.1, 0.2, 0.3\}$ 

### Without NumPy

In [2]:
li = [0.1, 0.2, 0.3]  # list of input numbers

In [3]:
cubic_li = [0, 0, 0]  # initialize a list

## Apply sine function to each number
number_of_elements = len(li)
for index in range(number_of_elements):
    cubic_li[index] = li[index] ** 3

In [4]:
cubic_li

[0.0010000000000000002, 0.008000000000000002, 0.026999999999999996]

In [5]:
# li ** 3  # this will raise an error

### With NumPy

In [6]:
array = np.array([0.1, 0.2, 0.3])  # define NumPy array for input numbers

In [7]:
array ** 3

array([0.001, 0.008, 0.027])

### Note that this is just an one example

# [ NumPy Array ]

## Constructing a N-D array

In [8]:
a1 = np.array([3,4,1])  # 1-D array

In [9]:
a1

array([3, 4, 1])

In [10]:
a2 = np.array([[1,2],[3,4],[5,6]])  # 2-D array

In [11]:
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
a3 = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]],[[5,5,5],[6,6,6]]])  # 3-D array

In [13]:
a3

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]],

       [[5, 5, 5],
        [6, 6, 6]]])

## Get some information of an array

### 1-D case

In [14]:
a1

array([3, 4, 1])

In [15]:
a1.ndim  # 'ndim' is a dimension of an array

1

In [16]:
a1.size  # 'size' is the total number of elements of this array

3

In [17]:
a1.shape  # 'shape' is a tuple of numbers of elements for each dimension

(3,)

In [18]:
len(a1)

3

### 2-D case

In [19]:
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
a2.ndim

2

In [21]:
a2.size

6

In [22]:
a2.shape

(3, 2)

In [23]:
len(a2) # Note in 2 or more dimensional array, 'length' and 'size' are not same

3

### 3-D case

In [24]:
a3

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]],

       [[5, 5, 5],
        [6, 6, 6]]])

In [25]:
a3.ndim

3

In [26]:
a3.size

18

In [27]:
a3.shape

(3, 2, 3)

In [28]:
len(a3)

3

# [ Array indexing / slicing ]
**Indexing (slicing)** array is specifying a portion of the array

## For 1D array

In [29]:
a1 = np.array([1,3,5,7,9])

### Slicing single element of 1D array

In [30]:
a1

array([1, 3, 5, 7, 9])

In [31]:
a1[0]

1

In [32]:
a1[2]

5

In [33]:
a1[4]

9

In [34]:
a1[-1]

9

In [35]:
a1[-2]

7

### Slicing multiple elements of 1D array
`a[i:j]` specify `i`-th element, (`i+1`)-th element, ..., (`j-1`)-th element of array `a`

**Note** that the last element `j` is _excluded_

In [36]:
a1

array([1, 3, 5, 7, 9])

In [37]:
a1[0:2]  # specifying a1[0], a1[1] (without a1[2])

array([1, 3])

In [38]:
a1[:2]  # same as a1[0:2], omitting zero (0)

array([1, 3])

In [39]:
a1[2:]  # specifying a1[2], a1[3], ..., a1[-1]

array([5, 7, 9])

In [40]:
a1[2:-1]  # Note that this is isn't same as a1[2:-1] since a1[-1] is omitted

array([5, 7])

In [41]:
a1[:]  # if one omits both start index and end index, it means all

array([1, 3, 5, 7, 9])

## For 2D array

In [42]:
a2 = np.array([[1,2],[3,4],[5,6]])

### Slicing single elements of 2D array

In [43]:
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
a2[0,0]

1

In [45]:
a2[0,1]

2

In [46]:
a2[1,0]

3

In [47]:
a2[0,-1]

2

In [48]:
a2[1,-2]

3

In [49]:
a2[-1,-1]

6

### Slicing Multiple elements of 2D array

In [50]:
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
a2[0]

array([1, 2])

In [52]:
row1 = a2[0]

In [53]:
row1[0]

1

In [54]:
row1[0] == a2[0,0]

True

In [55]:
a2[0][0] == a2[0,0]

True

In [56]:
a2[2][1] == a2[2,1]

True

In [57]:
a2[2] == a2[2,:]

array([ True,  True])

In [58]:
a2[1,:]

array([3, 4])

In [59]:
a2[:,1]

array([2, 4, 6])

# [ Array arithmetic ]
- [NOTE] This capability make it different from 'list' object or any other 'array-like' objects

In [60]:
a = np.array([1, 2, 3])
b = np.array([1, 1, 1])

### Addition : $+ / -$

In [61]:
a + b

array([2, 3, 4])

In [62]:
a - b

array([0, 1, 2])

### Scalar multplication

#### It is an element-wise operation

In [63]:
a * 2

array([2, 4, 6])

### multiplication : matrix - vector

In [64]:
a1 = np.array([1,1,1])
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [65]:
a1

array([1, 1, 1])

In [66]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
a1 @ a2

array([12, 15, 18])

In [68]:
a2 @ a1

array([ 6, 15, 24])

In [69]:
a2 @ a2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# [ Boolean operation ]

## NumPy array also supports logical operator (`==`, `!=`, `<`, `>` etc.)

### Scalar case

In [70]:
a = 3
b = 1
c = 2

In [71]:
a == b + c

True

In [72]:
a > c

True

### Array case

In [73]:
a1 = np.array([1,2,3])
b1 = np.array([0,1,2])
c1 = np.array([1,1,1])

In [74]:
a1 == b1 + c1

array([ True,  True,  True])

In [75]:
a1 > c1

array([False,  True,  True])

## Slicing using boolean array

In [76]:
a1 = np.array([1,3,5,7])

In [77]:
bool_array = np.array([True, False, False, True])

In [78]:
a1[bool_array]

array([1, 7])

### Example : for an array `array([0,1,2,3])`, get elements which is bigger than `1`

In [79]:
a1 = np.array([0,1,2,3])

In [80]:
mask = a1 > 1  # it will generate a boolean array

In [81]:
a1[mask]  # the boolean array 'mask' will select (slice) elements where element of mask is True

array([2, 3])